# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  app.sitename: 'Twist Around the Rock'
  app.carrousel.image.folder: '%kernel.project_dir%/public/images/carrousel_images/'
  app.article.image.folder: '%kernel.project_dir%/public/images/article_images/'
  app.product.image.folder: '%kernel.project_dir%/public/images/product_images/'
  app.about.image.folder: '%kernel.project_dir%/public/images/about_images/'
  app.about.carrousel.image.folder: '%kernel.project_dir%/public/images/about_carrousel_images/'
  app.product.carrousel.image.folder: '%kernel.project_dir%/public/images/product_carrousel_images/'
  app.article.carrousel.image.folder: '%kernel.project_dir%/public/images/article_carrousel_images/'

#  Stockage et cache des images pour Glide
  app.public_dir: '%kernel.project_dir%/public/images'
  app.image_cache_dir: '%kernel.project_dir%/var/storage/cache'
  app.public_dir.carrousel_images: '%kernel.project_dir%/public/images/carrousel_images'
  app.image_cache_dir.carrousel_images: '%kernel.project_dir%/var/storage/cache/images/carrousel_images'
  app.public_dir.about_carrousel_images: '%kernel.project_dir%/public/images/about_carrousel_images'
  app.image_cache_dir.about_carrousel_images: '%kernel.project_dir%/var/storage/cache/images/about_carrousel_images'
  app.public_dir.about_images: '%kernel.project_dir%/public/images/about_images'
  app.image_cache_dir.about_images: '%kernel.project_dir%/var/storage/cache/images/about_images'
  app.public_dir.article_carrousel_images: '%kernel.project_dir%/public/images/article_carrousel_images'
  app.image_cache_dir.article_carrousel_images: '%kernel.project_dir%/var/storage/cache/images/article_carrousel_images'
  app.public_dir.article_images: '%kernel.project_dir%/public/images/article_images'
  app.image_cache_dir.article_images: '%kernel.project_dir%/var/storage/cache/images/article_images'
  app.public_dir.product_carrousel_images: '%kernel.project_dir%/public/images/product_carrousel_images'
  app.image_cache_dir.product_carrousel_images: '%kernel.project_dir%/var/storage/cache/images/product_carrousel_images'
  app.public_dir.product_images: '%kernel.project_dir%/public/images/product_images'
  app.image_cache_dir.product_images: '%kernel.project_dir%/var/storage/cache/images/product_images'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
